upstreamProjects:
  Mule-runtime/mule-api/1.3.0-JULY-2022-WITH-FIXES-W-11403067-W-11147961
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
enableMavenTestStage: false
